// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZAlert.Api.Infrastructure.Persistence;

#nullable disable

namespace ZAlert.Api.Migrations
{
    [DbContext(typeof(ZAlertContext))]
    partial class ZAlertContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DependenteIdDepen")
                        .HasColumnType("integer");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SttsAlerta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAlerta");

                    b.HasIndex("DependenteIdDepen");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Dependente", b =>
                {
                    b.Property<int>("IdDepen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepen"));

                    b.Property<int>("IdadeDepen")
                        .HasColumnType("integer");

                    b.Property<string>("NmDepen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioIdUsu")
                        .HasColumnType("integer");

                    b.HasKey("IdDepen");

                    b.HasIndex("UsuarioIdUsu");

                    b.ToTable("Dependentes");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Dispositivo", b =>
                {
                    b.Property<int>("IdDisposit")
                        .HasColumnType("integer");

                    b.Property<string>("StatusDisposit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDisposit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDisposit");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Localizacao", b =>
                {
                    b.Property<int>("IdLocali")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLocali"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DependenteIdDepen")
                        .HasColumnType("integer");

                    b.Property<decimal>("LatLocali")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LngLocali")
                        .HasColumnType("numeric");

                    b.HasKey("IdLocali");

                    b.HasIndex("DependenteIdDepen");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Usuario", b =>
                {
                    b.Property<int>("IdUsu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsu"));

                    b.Property<string>("EmailUsu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NmUsu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaUsu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsu");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Alerta", b =>
                {
                    b.HasOne("ZAlert.Api.Domain.Entity.Dependente", "Dependente")
                        .WithMany("Alertas")
                        .HasForeignKey("DependenteIdDepen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependente");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Dependente", b =>
                {
                    b.HasOne("ZAlert.Api.Domain.Entity.Usuario", "Usuario")
                        .WithMany("Dependentes")
                        .HasForeignKey("UsuarioIdUsu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Dispositivo", b =>
                {
                    b.HasOne("ZAlert.Api.Domain.Entity.Dependente", "Dependente")
                        .WithOne("Dispositivo")
                        .HasForeignKey("ZAlert.Api.Domain.Entity.Dispositivo", "IdDisposit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependente");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Localizacao", b =>
                {
                    b.HasOne("ZAlert.Api.Domain.Entity.Dependente", "Dependente")
                        .WithMany("Localizacoes")
                        .HasForeignKey("DependenteIdDepen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependente");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Dependente", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Dispositivo");

                    b.Navigation("Localizacoes");
                });

            modelBuilder.Entity("ZAlert.Api.Domain.Entity.Usuario", b =>
                {
                    b.Navigation("Dependentes");
                });
#pragma warning restore 612, 618
        }
    }
}
